- name: Install nginx
  package:
    name:
      - nginx 
      - net-tools
      - apache2-utils
    state: present
  tags: nginx

- name: Basic auth configuration
  shell: "sudo htpasswd -b -c /etc/nginx/.htpasswd {{ basic_auth_user }} {{ basic_auth_password }}"
  tags: nginx

- name: Create Nginx virtualhost
  template: 
    src: nginx_virtualhost.j2
    dest: "/etc/nginx/sites-available/vault.conf"
  tags: nginx

- name: Enable Nginx virtualbox
  file:
    src: "/etc/nginx/sites-available/vault.conf" 
    dest: "/etc/nginx/sites-enabled/vault.conf"
    state: link
  notify:
    - restart nginx
  tags: nginx


- name: Create custom Vault policy
  template:
    src: policy.hcl.j2
    dest: "{{ vault_policy_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  tags:
    - policy

- name: Get root token
  debug: 
    msg: "{{ lookup('file', 'rootKey/rootkey') }}"
  register: root_token
  tags: 
    - policy
    - secrets
    - versioning

- name: Add custom Vault policy
  shell: "vault login {{ root_token.msg }} && vault policy write custom-policy {{ vault_policy_path }}"
  environment:
    VAULT_ADDR: "https://127.0.0.1:8200"
    VAULT_SKIP_VERIFY: "true"
  tags: policy

- name: Enable versioning
  shell: "vault login {{ root_token.msg }} && vault secrets enable -version=2 -path=secrets kv"
  environment:
    VAULT_ADDR: "https://127.0.0.1:8200"
    VAULT_SKIP_VERIFY: "true"
  tags: versioning
  ignore_errors: yes

- name: Add web secret in Vault
  shell: "vault login {{ root_token.msg }} && vault kv put -mount=secrets web admin=pa$$w0rd"
  environment:
    VAULT_ADDR: "https://127.0.0.1:8200"
    VAULT_SKIP_VERIFY: "true"
  tags: secrets

- name: Add database secret in Vault
  shell: "vault login {{ root_token.msg }} && vault kv put -mount=secrets database root=password"
  environment:
    VAULT_ADDR: "https://127.0.0.1:8200"
    VAULT_SKIP_VERIFY: "true"
  tags: secrets