

- name: Add GPG key
  shell: wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  run_once: true

- name: Add repo
  apt_repository:
    filename: hashicorp.list
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com jammy main'
    state: present

- name: Install vault
  apt:
    name: vault
    state: latest
    update_cache: yes

- name: Creating vault user group
  group: 
    name: "{{ vault_group }}"
  become: true

- name: Creating vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "vault nologin User"
    createhome: "no"
    state: present

# - name: config file
#   template:
#     src: vault.hcl.j2
#     dest: "{{ vault_config_path }}"
#     owner: "{{ vault_user }}"
#     group: "{{ vault_group }}"

- name: Configure vault.env
  blockinfile: |
    dest=/etc/vault.d/vault.env
    content="VAULT_API_ADDR=https://127.0.0.1:8200
      VAULT_API_SKIP_VERIFY=true"

- name: vault service
  service:
    name: vault
    state: restarted
    enabled: yes